version: "3.5"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - api_host=/backend
        - api_prefix=/api
        - path_prefix=
    image: frontend:__COMMIT_TAG__
