version: "3.5"

services:
  frontend:
    image: freeyeti/dev-in-docker:node-16-yarn-2
    env_file: ../.env
    environment:
      - NODE_ENV=development
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - ../:/code
